### ISSUE TITLE
Axios error

### ISSUE THREAD

**Issue by garrettboatman** [Elkfox/Concrete#83]
Everything appears to be working, but all of my team gets this axios error after `yarn start` or `yarn deploy`.

![Screen Shot 2019-11-20 at 11 26 15 AM](https://user-images.githubusercontent.com/3833961/69270865-b0546480-0b88-11ea-9aa4-d37478b8cb80.png)

```
(node:35580) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/garrettboatman/repos/byte-www/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/garrettboatman/repos/byte-www/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/garrettboatman/repos/byte-www/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
```

Any ideas?

**Comment by cam** [comment]
Hey @garrettboatman. We're getting the same error with the current build.

This is an issue with Slate Analytics. You can see the relevant issue at https://github.com/Shopify/slate/issues/1075

This issue includes a fix that is quite suitable until a new version is shipped. Essentially you should change line 95 of _node_modules/@shopify/slate-analytics/index.js_ to `return axios('https://v.shopify.com/slate/track', axiosConfig).catch(() => {});`. This ensures the script will bail silently if there is an error.

**Comment by garrettboatman** [comment]
@Cam Thank you! I couldn't find that Slate gh issue.

and thanks for the quick fix tip 🙂

**Comment by cam** [comment]
@garrettboatman no problem!
